export default {
  DATEPICKER: 'DATEPICKER',
  PICKER: 'PICKER',
  TEXTINPUT_ARRAY: 'TEXTINPUT_ARRAY',
  CHOICELIST: 'CHOICELIST',
  INITIAL_INSPECTION: 'INITIAL_INSPECTION',
  ROUTINE_INSPECTION: 'ROUTINE_INSPECTION',
  FOLLOWUP_INSPECTION: 'FOLLOWUP_INSPECTION',
};
